version: '3.8'

services:
  db:
    image: postgres
    container_name: my_postgres_db  # Nome fixo para o container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: the_walking_dead 
    volumes:
      - ./SQL/DDL.sql:/docker-entrypoint-initdb.d/0DDL.sql
      - ./SQL/Triggers_e_SP.sql:/docker-entrypoint-initdb.d/1Triggers_e_SP.sql
      - ./SQL/DML.sql:/docker-entrypoint-initdb.d/2DML.sql
      - ./SQL/create_user.sql:/docker-entrypoint-initdb.d/3create_user.sql
    expose:
      - "5432"
    restart: always
    networks: 
      - postgres-connection

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:80"
    networks: 
      - postgres-connection

networks:
  postgres-connection:
    driver: bridge
