begin;
CREATE USER jogo WITH PASSWORD 'senhasegura';
GRANT CONNECT ON DATABASE the_walking_dead TO jogo;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jogo;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jogo;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO jogo;
GRANT ALL PRIVILEGES ON DATABASE IN the_walking_dead TO jogo;

commit;